### ISSUE TITLE
Request for maintainers

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/FSharp.AWS.DynamoDB#10]
I'm no longer in a capacity to maintain this library, currently working exclusively with Azure at a direct competitor of Amazon's. This is a public request for new maintainers, who could potentially also sponsor AWS resources for driving tests.

**Comment by AviAvni** [comment]
I can help with maintain the code also maybe for testing we can use local dynamodb it's free and work great for local environment

**Comment by eiriktsarpalis** [comment]
Hey @AviAvni, are you still able to follow up on issues for this project? If not, my intention is to add an unmaintained.tech badge at the top of the readme file. I haven't used AWS in quite a while, so not able to reasonably respond to bug requests here.
