### ISSUE TITLE
Feature Request: BatchDeleteItemsAsync to return the TableKeys that failed to be deleted

### ISSUE THREAD

**Issue by pgeadas** [fsprojects/FSharp.AWS.DynamoDB#17]
### Expected behavior

BatchDeleteItemsAsync returns an Async<TabkeKey[]>

### Actual behavior

BatchDeleteItemsAsync returns an Async of unit

### Reason
This would be nice, so we can retry failed items.

Would this be possible? Thank you

**Comment by samritchie** [comment]
@pgeadas returning unprocessed keys is consistent with the Dynamo API so I think this is a worthwhile addition. It will be a breaking change so I’ll want to bundle up a release with a few other changes. Would you have any capacity to help out with this change?

**Comment by pgeadas** [comment]
Hi Sam.

This seems an easy solution, just making the function returning "return response.UnprocessedItems.[tableName] |> Seq.map (fun wr -> template.OfAttributeValues wr.DeleteRequest.Key)", however I cannot test this since this lib is still using .netCore 2.0, whichis too old and does not work under Manjaro (I have 3.0 currently only).

Is it possible to update it to a more recent version of .net, like the new LTS version (3.1) and then continue towards applying the patch?

**Comment by samritchie** [comment]
Yes, we should be able to bump to netstandard2.1 (and netcoreapp3.1 for the tests). I’m trying to work out what’s going on with the build scripts at the moment, although I am able to build/run/test the project as-is using dotnet 3.1.201 on macOS.

`template.OfAttributeValues` is expecting to unpickle a full record but I’ve built the equivalent for a key - I’ll let you know once it’s available.
