### ISSUE TITLE
PutItem precondition not working as expected

### ISSUE THREAD

**Issue by afshawnlotfi** [fsprojects/FSharp.AWS.DynamoDB#18]
### Description

Precondition on PutItem isn't working as expected. 

### Repro steps

1. Add item with same Guid
```fsharp
table.PutItemAsync (newEntry, precondition = (<@ fun entry -> entry.Guid <> newEntry.Guid @>))
```

### Expected behavior
Throw an exception because entry with that Guid has already been added

### Actual behavior
Exception is not thrown and item is added

### Known workarounds

No work arounds yet

### Related information 

*AWSSDK.DynamoDBv2 Version="3.3.101.58"
*FSharp.AWS.DynamoDB Version="0.8.0-beta"
*.Net CLI 2.2.401
*MacOs 10.14.4 (18E227)

**Comment by samritchie** [comment]
@afshawnlotfi I wasn’t able to reproduce this one, sorry - could you give a bit more detail on what you were trying to do here?
