### ISSUE TITLE
Question: How do you construct a TableKey for getItem?

### ISSUE THREAD

**Issue by allumbra** [fsprojects/FSharp.AWS.DynamoDB#19]
The item "client.GetItem"  takes a TableKey, but the TableKey constructor only takes unit.  What is the proper way to construct a TableKey to pass to GetItem?

In the docs and unit tests I only see examples of a key being returned from PutItem

**Comment by samritchie** [comment]
@allumbra - You use either `TableKey.Hash {hashKey}` or `TableKey.Combined ({hashKey}, {rangeKey})`
