### ISSUE TITLE
Updating with Map.remove raises Exception

### ISSUE THREAD

**Issue by afshawnlotfi** [fsprojects/FSharp.AWS.DynamoDB#20]
### Description

I tried using the Map.remove update expression and an exception was raised

I have tracked the issue down to https://github.com/fsprojects/FSharp.AWS.DynamoDB/blob/2d4c9211ac02f5c298ffc122babfef8bbbfb6aaf/src/FSharp.AWS.DynamoDB/Expression/UpdateExpr.fs#L329

### Repro steps

```fsharp
        table.Template.PrecomputeUpdateExpr
            <@ fun (sessionId : string) (entry: SessionModel) ->
                { entry with UserSessions = entry.UserSessions |> Map.remove sessionId  } @>
```
Specifically doesn't work for Precomputed Expressions
### Expected behavior

Remove item from map and not raise exception

### Actual behavior

Throws exception:
``
{Amazon.DynamoDBv2.AmazonDynamoDBException: Invalid UpdateExpression: Syntax error; token: "<", near: "#ATTR3<$" ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.\n   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:line 539\n   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 175\n   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)\n   --- End of inner exception stack trace ---\n   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 60\n   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 212\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 104\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 79\n   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 137\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at FSharp.Control.Tasks.TaskBuilder.bindTask@121.Invoke(Unit unitVar0) in C:\Users\humbo\source\repos\TaskBuilder.fs\TaskBuilder.fs:line 121\n   at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch) in C:\Users\humbo\source\repos\TaskBuilder.fs\TaskBuilder.fs:line 165}
``

### Known workarounds

Not using Precomputed expressions arguments which weren't really tested for Map update expressions. Instead pass the arguments into a separate function.
```fsharp
    let RemoveSession(table: TableContext<SessionModel>) (sessionId : string) =
        table.Template.PrecomputeUpdateExpr
            <@ fun (entry: SessionModel) ->
                {entry with UserSessions = entry.UserSessions |> Map.remove sessionId } @>

```

Related information
*AWSSDK.DynamoDBv2 Version="3.3.101.58"
*FSharp.AWS.DynamoDB Version="0.8.0-beta"
*.Net CLI 2.2.401
*MacOs 10.14.4 (18E227)

**Comment by samritchie** [comment]
@afshawnlotfi yes, it looks like it will be difficult to support parameterised map keys for add/remove operations on precomputed update expressions. I’ll see if I can add a descriptive exception message on this one for now.

**Comment by samritchie** [comment]
@afshawnlotfi turned out to be a simple fix after all once I worked out `Map.add` was working. Thanks for the bug report!
