### ISSUE TITLE
Question: how to delete a record without the table key?

### ISSUE THREAD

**Issue by thomasd3** [fsprojects/FSharp.AWS.DynamoDB#28]
When I put data in a table, I provide a hash key and then I get a table key once the data is inserted.

But I am not able to keep that table key.

Is it possible to build it from the hashkey? or do I need to do a query to find it (and if so, how does it work?)

**Comment by samritchie** [comment]
Yes, use `TableKey.Hash` to construct a `TableKey` from a hash (or `TableKey.Combined` if you also have a range key)
