### ISSUE TITLE
Invalid record field name starting with underscore

### ISSUE THREAD

**Issue by Rajivhost** [fsprojects/FSharp.AWS.DynamoDB#29]
Hi all,

Having such a table below:

![image](https://user-images.githubusercontent.com/3539984/97776108-e3a7bd80-1b65-11eb-86e3-127b4d327b5f.png)

and try to update a field from my code with Item having:

![image](https://user-images.githubusercontent.com/3539984/97776165-308b9400-1b66-11eb-843b-46237ff6af26.png)

I got error:

![image](https://user-images.githubusercontent.com/3539984/97776199-6df02180-1b66-11eb-8290-5e087be86dea.png)

I think, the CustomNameAttribute need to support such cases

**Comment by Rajivhost** [comment]
This [regex ](https://github.com/fsprojects/FSharp.AWS.DynamoDB/blob/89ed43f10a199a28ff84a52eee0e8f0b66d3244d/src/FSharp.AWS.DynamoDB/Utils/DynamoUtils.fs#L124) need to be updated and [this ](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html)need to be take in count.

**Comment by Rajivhost** [comment]
Using normal Amazon.DynamoDBv2 lib, I succeed

![image](https://user-images.githubusercontent.com/3539984/97777163-9da32780-1b6e-11eb-9dce-80fa8e7adf31.png)

![image](https://user-images.githubusercontent.com/3539984/97777168-a693f900-1b6e-11eb-9099-02ce65dacf17.png)

**Comment by samritchie** [comment]
Fixed in #33, thanks for reporting!
