### ISSUE TITLE
Feature Request: recursive record types

### ISSUE THREAD

**Issue by mjgpy3** [fsprojects/FSharp.AWS.DynamoDB#4]
This is a great library, very easy to use!

What are some of the difficulties in adding recursive record type support? I wouldn't mind taking a shot at the PR, I'm just not really sure if it's already been attempted.

**Comment by eiriktsarpalis** [comment]
I'm pretty certain it could be achieved, I intentionally avoided doing this b/c of implementation complexity.

**Comment by AviAvni** [comment]
@mjgpy3 Do you still interested with this?

**Comment by mjgpy3** [comment]
@AviAvni you can close it if you like.
