### ISSUE TITLE
Why is a scan all tautological?

### ISSUE THREAD

**Issue by mjgpy3** [fsprojects/FSharp.AWS.DynamoDB#5]
I'm trying to run

```
myTable.Scan <@ fun _ -> true @>
```

but am getting

> supplied query is tautological

Is there a reason for this?

Other client libraries tend to be alright with this, for example in the official document sdk client for node you can do

```
dynamodb.scan({
  TableName: myTableName
}, (error, data) => {
  if (error) {
     //...
  } else {
     //...
  }
});
```

**Comment by eiriktsarpalis** [comment]
@mjgpy3 this error was conceived to avoid accidentally posting tautological queries such as `¬φ ∧ φ`. Perhaps it could be relaxed, or provide a `Scan` overload that just returns everything.

**Comment by AviAvni** [comment]
@mjgpy3 do you still interested with this?

**Comment by mjgpy3** [comment]
@AviAvni you can close it if you like.
