### ISSUE TITLE
defaultArg/if_not_exists for the same attribute

### ISSUE THREAD

**Issue by matti-avilabs** [fsprojects/FSharp.AWS.DynamoDB#74]
I'm trying to figure out if there's any way to achieve the same end result as is given in the `Preventing overwrites of an existing attrubute` section from [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.PreventingAttributeOverwrites):

```
aws dynamodb update-item \
    --table-name ProductCatalog \
    --key '{"Id":{"N":"789"}}' \
    --update-expression "SET Price = if_not_exists(Price, :p)" \
    --expression-attribute-values '{":p": {"N": "100"}}' \
    --return-values ALL_NEW
```

So far I haven't been successful in any of my attempts so wondering if there's something I'm missing? From digging around it seems if `defaultArg` would be the way to go but as far as I can tell the only way to construct a valid update expression using that is if the attribute being set and the one passed into `defaultArg` are not the same ones.

I've tried the following but the resulting expressions are invalid in both cases:

For optional attributes: `SET p.Price (defaultArg p.Price price |> Some)`
For non-optional attributes: `SET p.Price (defaultArg (Some p.Price) price)`

**Comment by matti-avilabs** [comment]
Some findings from debugging a little bit:

For a successful case like from [here](https://github.com/fsprojects/FSharp.AWS.DynamoDB/blob/0f5bb4f42ff0cc88bce942b273f0ec5ffb514129/tests/FSharp.AWS.DynamoDB.Tests/UpdateExpressionTests.fs#L233-L244) the `String` attribute ends up being a part of the `bindings` Map via [this codepath](https://github.com/fsprojects/FSharp.AWS.DynamoDB/blob/0f5bb4f42ff0cc88bce942b273f0ec5ffb514129/src/FSharp.AWS.DynamoDB/Expression/UpdateExpr.fs#L152).

For the case mentioned in the issue where the attribute being set is the same one being used in the `defaultArg` call we end up [here](https://github.com/fsprojects/FSharp.AWS.DynamoDB/blob/0f5bb4f42ff0cc88bce942b273f0ec5ffb514129/src/FSharp.AWS.DynamoDB/Expression/UpdateExpr.fs#L153) and as a result the attribute isn't included in the `bindings` Map and we end up evaluating [this](https://github.com/fsprojects/FSharp.AWS.DynamoDB/blob/0f5bb4f42ff0cc88bce942b273f0ec5ffb514129/src/FSharp.AWS.DynamoDB/Expression/UpdateExpr.fs#L163).

Any ideas? @samritchie @bartelink

**Comment by samritchie** [comment]
I think the issue might be the update expression is `Some (defaultArg (attribute) (param))` and doesn’t match the specific handling of `defaultArg (attribute) (param)`. Unsure how to match on that, this is all in Eirik’s original code.

Don’t know whether we should support `defaultArg` on non-optionals - I understand why you’d want it but the expression comes across a bit nonsensical.

**Comment by matti-avilabs** [comment]
Thanks for looking into this, will be a very useful addition for us. And only being supported for optional fields is fine by me. I'm guessing that using the `UpdateOperators` syntax directly ends up as the same "stuff" as when using the standard record updates but it does look a bit more natural in that scenario `SET p.Price if NOT_EXISTS p.Price then 100 else p.Price`
